# --- User's custom definitions
USE_SLIC:=1
# ---

MAXCOMPILER_QUOTE   := $(shell printf %q "$(MAXCOMPILERDIR)")

RUNRULE_ARGS        := 
RUNRULE_RUNENV      := LD_LIBRARY_PATH="$(MAXELEROSDIR)/lib:$(LD_LIBRARY_PATH)" 
RUNRULE_MAXFILES    := SmithWaterman.max  
RUNRULE_MAXFILES_H  := SmithWaterman.h 
RUNRULE_CFLAGS      :=  -fPIC 
RUNRULE_LDFLAGS     :=  -shared 

TARGET_EXEC         := 
TARGET_LIBRARY      := libmaxlib.so


